title: PII Detector
description: >-
  This will annotate a document and send a message to the user when PII is found in a document or set of documents. 
type: object
documents:
  - selected
properties: 
  email:
    title: Detect e-mails?
    type: boolean
  phone:
    title: Detect phone numbers?
    type: boolean
