title: PII Detector
description: >-
  This add-on will detect PII in a document, annotate where, and automatically e-mail you when sensitive PII is detected if you choose that option.
type: object
documents:
  - query
  - selected
properties: 
  credit_card:
    title: Detect credit cards
    type: boolean
  email:
    title: Detect emails
    type: boolean
  phone:
    title: Detect phone numbers
    type: boolean
  address:
    title: Detect addresses
    type: boolean
  zip:
    title: Detect zipcodes
    type: boolean
  dob:
    title: Detect DOB
    type: boolean
  alert:
    title: Notify by email when PII is detected in a document
    type: boolean
