title: PII Detector
description: >-
  This will return a CSV file of all strings that match a valid credit card or social security number in a document. 
type: object
documents:
  - selected
properties:
  []
