title: PII Detector
description: >-
  This add-on will detect PII in a document and automatically e-mail you when sensitive PII is detected. It additionally gives you an option to search for e-mails, phone numbers, and addresses which will be e-mailed to you if detected. It optionally allows you to annotate the location of PII within a document.  
type: object
documents:
  - selected
properties: 
  email:
    title: Detect e-mails
    type: boolean
  phone:
    title: Detect phone numbers
    type: boolean
  address:
    title: Detect addresses
    type: boolean
  annotate:
    title: Do you want to annotate the document where PII is detected?
    type: boolean
  redact:
    title: Do you want to redact where PII is detected?
    type: boolean
