title: PII Detector
description: >-
  This add-on will detect PII in a document and automatically e-mail you when sensitive PII is detected. It will redact PII if selected, otherwise will just leave an annotation.
type: object
documents:
  - selected
properties: 
  email:
    title: Detect e-mails
    type: boolean
  phone:
    title: Detect phone numbers
    type: boolean
  address:
    title: Detect addresses
    type: boolean
  zip:
    title: Detect zipcodes
    type: boolean
  alert:
    title: Do you want an e-mail notification if PII was detected in a document?
    type: boolean
